# Generated by Django 5.1.2 on 2024-11-02 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('sport', models.CharField(max_length=128)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1080)),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('elevation', models.PositiveIntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
