# Generated by Django 5.1.2 on 2024-11-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(default='Corvallis, OR', max_length=128),
        ),
    ]
