# Generated by Django 5.1.2 on 2024-11-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='sport',
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=1080, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Distance (miles)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Duration (seconds)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elevation',
            field=models.PositiveIntegerField(verbose_name='Elevation (feet)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(default='Corvallis, OR', max_length=128, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
    ]
